Attaching to rinha2023q1_sql_nginx_1, rinha_sql_2, rinha_sql_1, my_pgadmin, rinha2023_db
[36mmy_pgadmin |[0m NOTE: Configuring authentication for SERVER mode.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m pgAdmin 4 - Application Initialisation
[36mmy_pgadmin |[0m ======================================
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m postfix/postlog: starting the Postfix mail system
[36mmy_pgadmin |[0m [2024-05-06 12:58:13 +0000] [1] [INFO] Starting gunicorn 20.1.0
[36mmy_pgadmin |[0m [2024-05-06 12:58:13 +0000] [1] [INFO] Listening at: http://[::]:5050 (1)
[36mmy_pgadmin |[0m [2024-05-06 12:58:13 +0000] [1] [INFO] Using worker: gthread
[36mmy_pgadmin |[0m [2024-05-06 12:58:13 +0000] [116] [INFO] Booting worker with pid: 116
[36mmy_pgadmin |[0m 2024-05-06 12:58:19,815: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[33mrinha2023_db |[0m The files belonging to this database system will be owned by user "postgres".
[33mrinha2023_db |[0m This user must also own the server process.
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m The database cluster will be initialized with locale "en_US.utf8".
[33mrinha2023_db |[0m The default database encoding has accordingly been set to "UTF8".
[33mrinha2023_db |[0m The default text search configuration will be set to "english".
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m Data page checksums are disabled.
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m fixing permissions on existing directory /var/lib/postgresql/data ... ok
[33mrinha2023_db |[0m creating subdirectories ... ok
[33mrinha2023_db |[0m selecting dynamic shared memory implementation ... posix
[33mrinha2023_db |[0m selecting default max_connections ... 100
[33mrinha2023_db |[0m selecting default shared_buffers ... 128MB
[33mrinha2023_db |[0m selecting default time zone ... Etc/UTC
[33mrinha2023_db |[0m creating configuration files ... ok
[33mrinha2023_db |[0m running bootstrap script ... ok
[33mrinha2023_db |[0m performing post-bootstrap initialization ... ok
[33mrinha2023_db |[0m syncing data to disk ... ok
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m Success. You can now start the database server using:
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m     pg_ctl -D /var/lib/postgresql/data -l logfile start
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m initdb: warning: enabling "trust" authentication for local connections
[33mrinha2023_db |[0m initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
[33mrinha2023_db |[0m waiting for server to start.... done
[33mrinha2023_db |[0m server started
[33mrinha2023_db |[0m CREATE DATABASE
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01_create_pessoas.sql
[33mrinha2023_db |[0m CREATE EXTENSION
[33mrinha2023_db |[0m CREATE TABLE
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02_procedures.sql
[33mrinha2023_db |[0m CREATE FUNCTION
[33mrinha2023_db |[0m CREATE FUNCTION
[33mrinha2023_db |[0m CREATE FUNCTION
[33mrinha2023_db |[0m CREATE FUNCTION
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/postgresql.conf
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m waiting for server to shut down..... done
[33mrinha2023_db |[0m server stopped
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m PostgreSQL init process complete; ready for start up.
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m 
[33mrinha2023_db |[0m PostgreSQL Database directory appears to contain a database; Skipping initialization
[33mrinha2023_db |[0m 
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:19 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:19,819: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:19 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:24,000: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:24 +0000] "GET /dashboard/dashboard_stats/2?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:24 +0000] "POST /misc/cleanup HTTP/1.1" 200 0 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:24,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:24 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:29,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[32mnginx_1    |[0m /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
[32mnginx_1    |[0m /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
[32mnginx_1    |[0m /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
[35mrinha_sql_1 |[0m start program
[35mrinha_sql_1 |[0m 2024/05/06 12:59:33 Database CONNECTED, URL:host=localhost port=5432 user=postgres password=postgres dbname=rinha sslmode=disable
[35mrinha_sql_1 |[0m 2024/05/06 12:59:33 oh wait, THERE IS A PORT
[35mrinha_sql_1 |[0m 2024/05/06 12:59:33 6969
[35mrinha_sql_1 |[0m 
[35mrinha_sql_1 |[0m     _______ __             
[35mrinha_sql_1 |[0m    / ____(_) /_  ___  _____
[35mrinha_sql_1 |[0m   / /_  / / __ \/ _ \/ ___/
[35mrinha_sql_1 |[0m  / __/ / / /_/ /  __/ /    
[35mrinha_sql_1 |[0m /_/   /_/_.___/\___/_/          v3.0.0-beta.2
[35mrinha_sql_1 |[0m --------------------------------------------------
[35mrinha_sql_1 |[0m INFO Server started on: 	http://127.0.0.1:6969 (bound on host 0.0.0.0 and port 6969)
[35mrinha_sql_1 |[0m INFO Total handlers count: 	5
[35mrinha_sql_1 |[0m INFO Prefork: 			Disabled
[35mrinha_sql_1 |[0m INFO PID: 			1
[35mrinha_sql_1 |[0m INFO Total process count: 	1
[35mrinha_sql_1 |[0m 
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:29 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:34,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:34 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:39,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:39 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:44,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:44 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:49,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[34mrinha_sql_2 |[0m start program
[34mrinha_sql_2 |[0m 2024/05/06 12:59:33 Database CONNECTED, URL:host=localhost port=5432 user=postgres password=postgres dbname=rinha sslmode=disable
[34mrinha_sql_2 |[0m 2024/05/06 12:59:33 oh wait, THERE IS A PORT
[34mrinha_sql_2 |[0m 2024/05/06 12:59:33 4200
[34mrinha_sql_2 |[0m 
[34mrinha_sql_2 |[0m     _______ __             
[34mrinha_sql_2 |[0m    / ____(_) /_  ___  _____
[34mrinha_sql_2 |[0m   / /_  / / __ \/ _ \/ ___/
[34mrinha_sql_2 |[0m  / __/ / / /_/ /  __/ /    
[34mrinha_sql_2 |[0m /_/   /_/_.___/\___/_/          v3.0.0-beta.2
[34mrinha_sql_2 |[0m --------------------------------------------------
[34mrinha_sql_2 |[0m INFO Server started on: 	http://127.0.0.1:4200 (bound on host 0.0.0.0 and port 4200)
[34mrinha_sql_2 |[0m INFO Total handlers count: 	5
[34mrinha_sql_2 |[0m INFO Prefork: 			Disabled
[34mrinha_sql_2 |[0m INFO PID: 			1
[34mrinha_sql_2 |[0m INFO Total process count: 	1
[34mrinha_sql_2 |[0m 
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:49 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:54,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:54 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:58:59,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:58:59 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m [2024-05-06 12:58:59 +0000] [1] [INFO] Handling signal: term
[36mmy_pgadmin |[0m postfix/postlog: starting the Postfix mail system
[36mmy_pgadmin |[0m [2024-05-06 12:59:06 +0000] [1] [INFO] Starting gunicorn 20.1.0
[36mmy_pgadmin |[0m [2024-05-06 12:59:06 +0000] [1] [INFO] Listening at: http://[::]:5050 (1)
[36mmy_pgadmin |[0m [2024-05-06 12:59:06 +0000] [1] [INFO] Using worker: gthread
[36mmy_pgadmin |[0m [2024-05-06 12:59:06 +0000] [82] [INFO] Booting worker with pid: 82
[36mmy_pgadmin |[0m 2024-05-06 12:59:12,623: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:12 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:14,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:14 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:19,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:19 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:23,999: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:24 +0000] "GET /dashboard/dashboard_stats/2?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:24,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:24 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:29,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:29 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
[36mmy_pgadmin |[0m 2024-05-06 12:59:34,235: ERROR	pgadmin:	400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 261, in protect
[36mmy_pgadmin |[0m     validate_csrf(self._get_csrf_token())
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 103, in validate_csrf
[36mmy_pgadmin |[0m     raise ValidationError("The CSRF session token is missing.")
[36mmy_pgadmin |[0m wtforms.validators.ValidationError: The CSRF session token is missing.
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m During handling of the above exception, another exception occurred:
[36mmy_pgadmin |[0m 
[36mmy_pgadmin |[0m Traceback (most recent call last):
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
[36mmy_pgadmin |[0m     rv = self.preprocess_request()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
[36mmy_pgadmin |[0m     rv = self.ensure_sync(before_func)()
[36mmy_pgadmin |[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 229, in csrf_protect
[36mmy_pgadmin |[0m     self.protect()
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 264, in protect
[36mmy_pgadmin |[0m     self._error_response(e.args[0])
[36mmy_pgadmin |[0m   File "/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 307, in _error_response
[36mmy_pgadmin |[0m     raise CSRFError(reason)
[36mmy_pgadmin |[0m flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
[36mmy_pgadmin |[0m ::1 - - [06/May/2024:12:59:34 +0000] "GET /dashboard/dashboard_stats/1/16384?chart_names=session_stats,tps_stats,ti_stats,to_stats,bio_stats HTTP/1.1" 400 125 "http://localhost:5050/browser/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
